# .zshrc
autoload -U colors
autoload -U compinit promptinit
autoload -U edit-command-line

setopt COMPLETE_IN_WORD
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt AUTO_CD
setopt NO_BEEP
setopt prompt_subst
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome

colors
compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

PROMPT='%{$fg_bold[green]%}%~ %{$reset_color%}%{$fg[white]%}✎ %{$reset_color%} '
RPROMPT='${vcs_info_msg_0_}%'

source "$HOME/.zsh/aliases.zsh"
#source "$HOME/.zsh/completion.zsh"
#source "$HOME/.zsh/edit_command_line.zsh"
source "$HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
#source "$HOME/.zsh/git.zsh"
#source "$HOME/.zsh/prompt.zsh"
#source "$HOME/.zsh/rbenv.zsh"
#source "$HOME/.zsh/rust.zsh"
#source "$HOME/.zsh/rsvm.zsh"
#source "$HOME/.zsh/golang.zsh"
#source "$HOME/.zsh/rust.zsh"
#source "$HOME/.zsh/less.zsh"

# Source any extra config that should not be
# in the public dotfiles repo
if [ -f "$HOME/.zsh/extras.zsh" ]; then
  source "$HOME/.zsh/extras.zsh"
fi

bindkey "\E[3~" delete-char
alias pacman='sudo pacman --noconfirm'
