set nocompatible
set path+=**
set wildmenu
syntax enable
filetype plugin on
command! MakeTags !ctags -R .
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab

au BufNewFile,BufRead *rtorrent.rc* set filetype=rtorrent
