#!/bin/sh

client_root=$HOME
server_uri=https://storageb.in

#TODO make this run to check for credentials, and ask for it if missing.
source ~/credentials

#sync this system with the base directories. 
nextcloudcmd --path /Configs -u $user -p $password $client_root/Configs $server_uri
#nextcloudcmd --path /Documents -u $user -p $password $client_root/Documents $server_uri
#nextcloudcmd --path /Notes -u $user -p $password $client_root/Notes $server_uri
# TODO change to Pictures on server
#nextcloudcmd --path /Photos -u $user -p $password $client_root/Photos $server_uri
#nextcloudcmd --path /Projects -u $user -p $password $client_root/Projects $server_uri
#TODO consider separating Projects to a dev file.
# for now I don't fully see the need, but I want to keep things well organize

