#!/bin/bash
# nextcloudcmd -u $user -p $password --path /Configs $client_root/Configs $server_uri
./Configs
# nextcloudcmd -u $user -p $password --path /Documents $client_root/Documents $server_uri
./Documents
# nextcloudcmd -u $user -p $password --path /Notes $client_root/Notes $server_uri
./Notes
# nextcloudcmd -u $user -p $password --path /Pictures $client_root/Pictures $server_uri
./Pictures
# nextcloudcmd -u $user -p $password --path /Projects $client_root/Projects $server_uri
./Projects
# TODO move Project to git
#      script to call these indvidually from anywhere
