#!/bin/sh

client_root=$HOME
server_uri=https://storageb.in

#TODO make this run to check for credentials, and ask for it if missing.
source ~/.credentials

# TODO make variables for the local path to make more versatile
nextcloudcmd -u $user -p $password --path "/Community/Shows/Gilmore Girls" $client_root/Downloads/Gilmore.Girls.Complete.S01-S07.REPACK.1080p.WEB-DL.x265.10bit.HEVC-MONOLITH $server_uri
